baseurl = "https://makerhanoi.github.io/"
title = "Maker Hanoi - Your contribution, we share"
theme = "hugo-universal-theme"
# themesDir = "../.."
languageCode = "vi"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "vi"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-80690443-1"

# Define the number of posts per page
paginate = 10

[languages]
  [languages.en]
    title = "Maker Hanoi - Your contribution, we share"
    weight = 1
  [languages.vi]
    title = "Maker Hanoi - Cùng đóng góp, cùng chia sẻ"
    weight = 2
    
[menu]

# Main menu

[[languages.vi.menu.main]]
    name = "Trang chủ"
    url  = "/"
    weight = 1

#[[languages.vi.menu.main]]
#    name = "Blog"
#    url  = "/blog/"
#    weight = 2

[[languages.vi.menu.main]]
    name = "Hỏi đáp"
    identifier = "faq"
    url  = "/faq/"
    weight = 2

[[languages.vi.menu.main]]
    name = "Liên hệ"
    url  = "/contact/"
    weight = 3


[[languages.vi.menu.main]]
    name = "Engish"
    url  = "/en"
    weight = 4

[[languages.en.menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[languages.en.menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 2

[[languages.en.menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 3

[[languages.en.menu.main]]
    name = "Tiếng Việt"
    url  = "/"
    weight = 4



# Top bar social links menu
[[languages.vi.menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/makerhanoi"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[languages.vi.menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/makerhanoi/"
    pre = "<i class='fa fa-2x fa-facebook'></i>"


[[languages.vi.menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:makerhanoi@gmail.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"


# Top bar social links menu
[[languages.en.menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/makerhanoi"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[languages.en.menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/makerhanoi/"
    pre = "<i class='fa fa-2x fa-facebook'></i>"


[[languages.en.menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:makerhanoi@gmail.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"


[languages.vi.params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "makerhanoi@gmail.com"

    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "Copyright (c) 2015 - 2016, MakerHanoi; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p><strong>MakerHanoi</strong>
        <br>29 Dương Khuê
        <br>Cầu Giấy
        <br>Hà nội
        <strong>Việt Nam</strong>
      </p>
      """
    latitude = "-12.043333"
    longitude = "-77.028333"


[languages.en.params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "makerhanoi@gmail.com"

    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "Copyright (c) 2015 - 2016, MakerHanoi; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p><strong>MakerHanoi</strong>
        <br>29 Duong Khue
        <br>Cau Giay
        <br>Ha noi
        <strong>Viet Nam</strong>
      </p>
      """
    latitude = "-12.043333"
    longitude = "-77.028333"


[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[languages.en.params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +84 85 999 9789 or makerhanoi@gmail.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

[languages.vi.params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Liện hệ với chúng tôi +84 85 999 9789 hoặc makerhanoi@gmail.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = false
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[languages.vi.params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Đối tác"
    subtitle = ""

[languages.en.params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Partners"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
